-- MySQL Script generated by MySQL Workbench
-- 05/12/15 20:34:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ordermgmt` ;

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordermgmt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ordermgmt` ;

-- -----------------------------------------------------
-- Table `ordermgmt`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`user` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`user` (
  `pk_id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_user`),
  UNIQUE INDEX `pk_idUser_UNIQUE` (`pk_id_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`table_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`table_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`table_status` (
  `pk_id_table_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_table_status`),
  UNIQUE INDEX `pk_id_table_status_UNIQUE` (`pk_id_table_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`restaurant_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`restaurant_table` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`restaurant_table` (
  `pk_id_restaurant_table` INT NOT NULL AUTO_INCREMENT,
  `max_person` INT NULL,
  `fk_id_table_status` INT NULL,
  `fk_id_waiter_status` INT NULL,
  PRIMARY KEY (`pk_id_restaurant_table`),
  UNIQUE INDEX `pk_id_restaurant_table_UNIQUE` (`pk_id_restaurant_table` ASC),
  INDEX `fk_table_table_status1_idx` (`fk_id_table_status` ASC),
  INDEX `fk_table_waiter_status1_idx` (`fk_id_waiter_status` ASC),
  CONSTRAINT `fk_table_table_status1`
    FOREIGN KEY (`fk_id_table_status`)
    REFERENCES `ordermgmt`.`table_status` (`pk_id_table_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table_waiter_status1`
    FOREIGN KEY (`fk_id_waiter_status`)
    REFERENCES `ordermgmt`.`waiter_status` (`pk_id_waiter_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`customer` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`customer` (
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` DATETIME NULL,
  `street` VARCHAR(45) NULL,
  `house_no` INT NULL,
  `post_code` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `fk_id_user` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`fk_id_user`),
  CONSTRAINT `fk_customer_user`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`user` (`pk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ordermgmt`.`reservation_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservation_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservation_status` (
  `pk_id_reservation_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_reservation_status`),
  UNIQUE INDEX `pk_id_reservation_status_UNIQUE` (`pk_id_reservation_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservation` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservation` (
  `pk_id_reservation` INT NOT NULL AUTO_INCREMENT,
  `time_from` TIMESTAMP NULL,
  `time_to` TIMESTAMP NULL,
  `persons` INT NULL,
  `reservation_col` VARCHAR(45) NULL,
  `fk_id_user` INT NULL,
  `fk_id_restaurant_table` INT NULL,
  `fk_id_reservation_status` INT NULL,
  PRIMARY KEY (`pk_id_reservation`),
  UNIQUE INDEX `pk_idReservation_UNIQUE` (`pk_id_reservation` ASC),
  INDEX `fk_reservation_customer1_idx` (`fk_id_user` ASC),
  INDEX `fk_reservation_table1_idx` (`fk_id_restaurant_table` ASC),
  INDEX `fk_reservation_reservation_status1_idx` (`fk_id_reservation_status` ASC),
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`customer` (`fk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_table1`
    FOREIGN KEY (`fk_id_restaurant_table`)
    REFERENCES `ordermgmt`.`restaurant_table` (`pk_id_restaurant_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_reservation_status1`
    FOREIGN KEY (`fk_id_reservation_status`)
    REFERENCES `ordermgmt`.`reservation_status` (`pk_id_reservation_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`bill_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`bill_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`bill_status` (
  `pk_id_bill_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_bill_status`),
  UNIQUE INDEX `pk_id_bill_status_UNIQUE` (`pk_id_bill_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`bill` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`bill` (
  `pk_id_bill` INT NOT NULL AUTO_INCREMENT,
  `issuing_date` DATETIME NULL,
  `fk_id_bill_status` INT NULL,
  PRIMARY KEY (`pk_id_bill`),
  UNIQUE INDEX `pk_idBill_UNIQUE` (`pk_id_bill` ASC),
  INDEX `fk_bill_bill_status1_idx` (`fk_id_bill_status` ASC),
  CONSTRAINT `fk_bill_bill_status1`
    FOREIGN KEY (`fk_id_bill_status`)
    REFERENCES `ordermgmt`.`bill_status` (`pk_id_bill_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order_status` (
  `pk_id_order_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_order_status`),
  UNIQUE INDEX `pk_id_order_status_UNIQUE` (`pk_id_order_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order` (
  `pk_id_order` INT NOT NULL AUTO_INCREMENT,
  `fk_id_order_status` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `creation_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_id_user` INT NULL,
  `fk_id_reservation` INT NULL,
  `fk_id_bill` INT NULL,
  PRIMARY KEY (`pk_id_order`),
  UNIQUE INDEX `idOrder_UNIQUE` (`pk_id_order` ASC),
  INDEX `fk_order_customer1_idx` (`fk_id_user` ASC),
  INDEX `fk_order_reservation1_idx` (`fk_id_reservation` ASC),
  INDEX `fk_order_bill1_idx` (`fk_id_bill` ASC),
  INDEX `fk_order_order_status1_idx` (`fk_id_order_status` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`customer` (`fk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_reservation1`
    FOREIGN KEY (`fk_id_reservation`)
    REFERENCES `ordermgmt`.`reservation` (`pk_id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_bill1`
    FOREIGN KEY (`fk_id_bill`)
    REFERENCES `ordermgmt`.`bill` (`pk_id_bill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`fk_id_order_status`)
    REFERENCES `ordermgmt`.`order_status` (`pk_id_order_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order_item_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order_item_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order_item_status` (
  `pk_id_order_item_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_order_item_status`),
  UNIQUE INDEX `pk_id_order_item_status_UNIQUE` (`pk_id_order_item_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`food_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`food_type` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`food_type` (
  `pk_id_food_type` INT NOT NULL AUTO_INCREMENT,
  `tax` DOUBLE NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_food_type`),
  UNIQUE INDEX `pk_id_food_type_UNIQUE` (`pk_id_food_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`size_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`size_unit` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`size_unit` (
  `pk_id_size_unit` INT NOT NULL AUTO_INCREMENT,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_size_unit`),
  UNIQUE INDEX `pk_id_size_unit_UNIQUE` (`pk_id_size_unit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`food` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`food` (
  `pk_id_food` INT NOT NULL AUTO_INCREMENT,
  `net_price` DOUBLE NULL,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `fk_id_food_type` INT NULL,
  `size` DOUBLE NULL,
  `fk_id_size_unit` INT NULL,
  PRIMARY KEY (`pk_id_food`),
  UNIQUE INDEX `pk_idFood_UNIQUE` (`pk_id_food` ASC),
  INDEX `fk_food_food_type1_idx` (`fk_id_food_type` ASC),
  INDEX `fk_food_size_unit1_idx` (`fk_id_size_unit` ASC),
  CONSTRAINT `fk_food_food_type1`
    FOREIGN KEY (`fk_id_food_type`)
    REFERENCES `ordermgmt`.`food_type` (`pk_id_food_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_size_unit1`
    FOREIGN KEY (`fk_id_size_unit`)
    REFERENCES `ordermgmt`.`size_unit` (`pk_id_size_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order_item` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order_item` (
  `pk_id_order_item` INT NOT NULL AUTO_INCREMENT,
  `fk_id_order_item_status` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `fk_id_order` INT NULL,
  `fk_id_food` INT NULL,
  PRIMARY KEY (`pk_id_order_item`),
  UNIQUE INDEX `id_order_item_UNIQUE` (`pk_id_order_item` ASC),
  INDEX `fk_order_item_order1_idx` (`fk_id_order` ASC),
  INDEX `fk_order_item_order_item_status1_idx` (`fk_id_order_item_status` ASC),
  INDEX `fk_order_item_food1_idx` (`fk_id_food` ASC),
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`fk_id_order`)
    REFERENCES `ordermgmt`.`order` (`pk_id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_order_item_status1`
    FOREIGN KEY (`fk_id_order_item_status`)
    REFERENCES `ordermgmt`.`order_item_status` (`pk_id_order_item_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_food1`
    FOREIGN KEY (`fk_id_food`)
    REFERENCES `ordermgmt`.`food` (`pk_id_food`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`test` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`test` (
  `pk_id_test` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_test`),
  UNIQUE INDEX `pk_idTest_UNIQUE` (`pk_id_test` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ordermgmt`.`waiter_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`waiter_status` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`waiter_status` (
  `pk_id_waiter_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_waiter_status`),
  UNIQUE INDEX `pk_id_waiter_status_UNIQUE` (`pk_id_waiter_status` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
