-- MySQL Script generated by MySQL Workbench
-- 05/12/15 10:18:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ordermgmt` ;

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordermgmt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ordermgmt` ;

-- -----------------------------------------------------
-- Table `ordermgmt`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`user` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`user` (
  `pk_idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idUser`),
  UNIQUE INDEX `pk_idUser_UNIQUE` (`pk_idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`tableStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`tableStatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`tableStatus` (
  `pk_idTableStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idTableStatus`),
  UNIQUE INDEX `pk_idTableStatus_UNIQUE` (`pk_idTableStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`table` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`table` (
  `pk_idTable` INT NOT NULL AUTO_INCREMENT,
  `maxPerson` INT NULL,
  `fk_idTableStatus` INT NULL,
  PRIMARY KEY (`pk_idTable`),
  UNIQUE INDEX `pk_idTable_UNIQUE` (`pk_idTable` ASC),
  INDEX `fk_table_tableStatus1_idx` (`fk_idTableStatus` ASC),
  CONSTRAINT `fk_table_tableStatus1`
    FOREIGN KEY (`fk_idTableStatus`)
    REFERENCES `ordermgmt`.`tableStatus` (`pk_idTableStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`customer` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`customer` (
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `dateOfBirth` DATETIME NULL,
  `street` VARCHAR(45) NULL,
  `houseNumber` VARCHAR(45) NULL,
  `postCode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `fk_idUser` INT NOT NULL,
  `fk_idTable` INT NULL,
  PRIMARY KEY (`fk_idUser`),
  INDEX `fk_customer_table1_idx` (`fk_idTable` ASC),
  CONSTRAINT `fk_customer_user`
    FOREIGN KEY (`fk_idUser`)
    REFERENCES `ordermgmt`.`user` (`pk_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_table1`
    FOREIGN KEY (`fk_idTable`)
    REFERENCES `ordermgmt`.`table` (`pk_idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`reservationStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservationStatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservationStatus` (
  `pk_idReservationStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idReservationStatus`),
  UNIQUE INDEX `pk_idReservationStatus_UNIQUE` (`pk_idReservationStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservation` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservation` (
  `pk_idReservation` INT NOT NULL AUTO_INCREMENT,
  `timeFrom` TIMESTAMP NULL,
  `timeTo` TIMESTAMP NULL,
  `persons` INT NULL,
  `reservationcol` VARCHAR(45) NULL,
  `fk_idUser` INT NULL,
  `fk_idTable` INT NULL,
  `fk_idReservationStatus` INT NULL,
  PRIMARY KEY (`pk_idReservation`),
  UNIQUE INDEX `pk_idReservation_UNIQUE` (`pk_idReservation` ASC),
  INDEX `fk_reservation_customer1_idx` (`fk_idUser` ASC),
  INDEX `fk_reservation_table1_idx` (`fk_idTable` ASC),
  INDEX `fk_reservation_reservationStatus1_idx` (`fk_idReservationStatus` ASC),
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`fk_idUser`)
    REFERENCES `ordermgmt`.`customer` (`fk_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_table1`
    FOREIGN KEY (`fk_idTable`)
    REFERENCES `ordermgmt`.`table` (`pk_idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_reservationStatus1`
    FOREIGN KEY (`fk_idReservationStatus`)
    REFERENCES `ordermgmt`.`reservationStatus` (`pk_idReservationStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`billStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`billStatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`billStatus` (
  `pk_idBillStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idBillStatus`),
  UNIQUE INDEX `pk_idBillStatus_UNIQUE` (`pk_idBillStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`bill` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`bill` (
  `pk_idBill` INT NOT NULL AUTO_INCREMENT,
  `issuingDate` DATETIME NULL,
  `fk_idBillStatus` INT NULL,
  PRIMARY KEY (`pk_idBill`),
  UNIQUE INDEX `pk_idBill_UNIQUE` (`pk_idBill` ASC),
  INDEX `fk_bill_billStatus1_idx` (`fk_idBillStatus` ASC),
  CONSTRAINT `fk_bill_billStatus1`
    FOREIGN KEY (`fk_idBillStatus`)
    REFERENCES `ordermgmt`.`billStatus` (`pk_idBillStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderStatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderStatus` (
  `pk_idOrderStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idOrderStatus`),
  UNIQUE INDEX `pk_idOrderStatus_UNIQUE` (`pk_idOrderStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order` (
  `pk_idOrder` INT NOT NULL AUTO_INCREMENT,
  `fk_idOrderStatus` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `creationTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idUser` INT NULL,
  `fk_idReservation` INT NULL,
  `fk_idBill` INT NULL,
  PRIMARY KEY (`pk_idOrder`),
  UNIQUE INDEX `idOrder_UNIQUE` (`pk_idOrder` ASC),
  INDEX `fk_order_customer1_idx` (`fk_idUser` ASC),
  INDEX `fk_order_reservation1_idx` (`fk_idReservation` ASC),
  INDEX `fk_order_bill1_idx` (`fk_idBill` ASC),
  INDEX `fk_order_orderStatus1_idx` (`fk_idOrderStatus` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`fk_idUser`)
    REFERENCES `ordermgmt`.`customer` (`fk_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_reservation1`
    FOREIGN KEY (`fk_idReservation`)
    REFERENCES `ordermgmt`.`reservation` (`pk_idReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_bill1`
    FOREIGN KEY (`fk_idBill`)
    REFERENCES `ordermgmt`.`bill` (`pk_idBill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_orderStatus1`
    FOREIGN KEY (`fk_idOrderStatus`)
    REFERENCES `ordermgmt`.`orderStatus` (`pk_idOrderStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderItemStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderItemStatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderItemStatus` (
  `pk_idOrderItemStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idOrderItemStatus`),
  UNIQUE INDEX `pk_idOrderItemStatus_UNIQUE` (`pk_idOrderItemStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`foodType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`foodType` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`foodType` (
  `pk_idFoodType` INT NOT NULL AUTO_INCREMENT,
  `tax` DOUBLE NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idFoodType`),
  UNIQUE INDEX `pk_idFoodType_UNIQUE` (`pk_idFoodType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`sizeUnit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`sizeUnit` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`sizeUnit` (
  `pk_idSizeUnit` INT NOT NULL AUTO_INCREMENT,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idSizeUnit`),
  UNIQUE INDEX `pk_idSizeUnit_UNIQUE` (`pk_idSizeUnit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`food` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`food` (
  `pk_idFood` INT NOT NULL AUTO_INCREMENT,
  `netPrice` DOUBLE NULL,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `fk_idFoodType` INT NULL,
  `size` DOUBLE NULL,
  `fk_idSizeUnit` INT NULL,
  PRIMARY KEY (`pk_idFood`),
  UNIQUE INDEX `pk_idFood_UNIQUE` (`pk_idFood` ASC),
  INDEX `fk_food_foodType1_idx` (`fk_idFoodType` ASC),
  INDEX `fk_food_sizeUnit1_idx` (`fk_idSizeUnit` ASC),
  CONSTRAINT `fk_food_foodType1`
    FOREIGN KEY (`fk_idFoodType`)
    REFERENCES `ordermgmt`.`foodType` (`pk_idFoodType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_sizeUnit1`
    FOREIGN KEY (`fk_idSizeUnit`)
    REFERENCES `ordermgmt`.`sizeUnit` (`pk_idSizeUnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderItem` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderItem` (
  `pk_idOrderItem` INT NOT NULL AUTO_INCREMENT,
  `fk_idOrderItemStatus` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `fk_idOrder` INT NULL,
  `fk_idFood` INT NULL,
  PRIMARY KEY (`pk_idOrderItem`),
  UNIQUE INDEX `idOrderItem_UNIQUE` (`pk_idOrderItem` ASC),
  INDEX `fk_orderItem_order1_idx` (`fk_idOrder` ASC),
  INDEX `fk_orderItem_orderItemStatus1_idx` (`fk_idOrderItemStatus` ASC),
  INDEX `fk_orderItem_food1_idx` (`fk_idFood` ASC),
  CONSTRAINT `fk_orderItem_order1`
    FOREIGN KEY (`fk_idOrder`)
    REFERENCES `ordermgmt`.`order` (`pk_idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItem_orderItemStatus1`
    FOREIGN KEY (`fk_idOrderItemStatus`)
    REFERENCES `ordermgmt`.`orderItemStatus` (`pk_idOrderItemStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItem_food1`
    FOREIGN KEY (`fk_idFood`)
    REFERENCES `ordermgmt`.`food` (`pk_idFood`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`test` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`test` (
  `pk_idTest` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idTest`),
  UNIQUE INDEX `pk_idTest_UNIQUE` (`pk_idTest` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
