-- MySQL Script generated by MySQL Workbench
-- 05/12/15 20:34:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ordermgmt` ;

-- -----------------------------------------------------
-- Schema ordermgmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordermgmt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ordermgmt` ;

-- -----------------------------------------------------
-- Table `ordermgmt`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`user` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`user` (
  `pk_id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_user`),
  UNIQUE INDEX `pk_idUser_UNIQUE` (`pk_id_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`tablestatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`tablestatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`tablestatus` (
  `pk_id_tablestatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_tablestatus`),
  UNIQUE INDEX `pk_idTableStatus_UNIQUE` (`pk_id_tablestatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`table` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`table` (
  `pk_id_table` INT NOT NULL AUTO_INCREMENT,
  `max_person` INT NULL,
  `fk_id_tablestatus` INT NULL,
  PRIMARY KEY (`pk_id_table`),
  UNIQUE INDEX `pk_idTable_UNIQUE` (`pk_id_table` ASC),
  INDEX `fk_table_tableStatus1_idx` (`fk_id_tablestatus` ASC),
  CONSTRAINT `fk_table_tableStatus1`
    FOREIGN KEY (`fk_id_tablestatus`)
    REFERENCES `ordermgmt`.`tablestatus` (`pk_id_tablestatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`customer` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`customer` (
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `date_birth` DATETIME NULL,
  `street` VARCHAR(45) NULL,
  `houseno` INT NULL,
  `postcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `fk_id_user` INT NOT NULL,
  `fk_id_table` INT NULL,
  PRIMARY KEY (`fk_id_user`),
  INDEX `fk_customer_table1_idx` (`fk_id_table` ASC),
  CONSTRAINT `fk_customer_user`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`user` (`pk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_table1`
    FOREIGN KEY (`fk_id_table`)
    REFERENCES `ordermgmt`.`table` (`pk_id_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`reservationstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservationstatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservationstatus` (
  `pk_id_reservationstatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_reservationstatus`),
  UNIQUE INDEX `pk_idReservationStatus_UNIQUE` (`pk_id_reservationstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`reservation` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`reservation` (
  `pk_id_reservation` INT NOT NULL AUTO_INCREMENT,
  `time_from` TIMESTAMP NULL,
  `time_to` TIMESTAMP NULL,
  `persons` INT NULL,
  `reservationcol` VARCHAR(45) NULL,
  `fk_id_user` INT NULL,
  `fk_id_table` INT NULL,
  `fk_id_reservationstatus` INT NULL,
  PRIMARY KEY (`pk_id_reservation`),
  UNIQUE INDEX `pk_idReservation_UNIQUE` (`pk_id_reservation` ASC),
  INDEX `fk_reservation_customer1_idx` (`fk_id_user` ASC),
  INDEX `fk_reservation_table1_idx` (`fk_id_table` ASC),
  INDEX `fk_reservation_reservationStatus1_idx` (`fk_id_reservationstatus` ASC),
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`customer` (`fk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_table1`
    FOREIGN KEY (`fk_id_table`)
    REFERENCES `ordermgmt`.`table` (`pk_id_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_reservationStatus1`
    FOREIGN KEY (`fk_id_reservationstatus`)
    REFERENCES `ordermgmt`.`reservationstatus` (`pk_id_reservationstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`billstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`billstatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`billstatus` (
  `pk_id_billstatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_billstatus`),
  UNIQUE INDEX `pk_idBillStatus_UNIQUE` (`pk_id_billstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`bill` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`bill` (
  `pk_id_bill` INT NOT NULL AUTO_INCREMENT,
  `issuing_date` DATETIME NULL,
  `fk_id_billstatus` INT NULL,
  PRIMARY KEY (`pk_id_bill`),
  UNIQUE INDEX `pk_idBill_UNIQUE` (`pk_id_bill` ASC),
  INDEX `fk_bill_billStatus1_idx` (`fk_id_billstatus` ASC),
  CONSTRAINT `fk_bill_billStatus1`
    FOREIGN KEY (`fk_id_billstatus`)
    REFERENCES `ordermgmt`.`billstatus` (`pk_id_billstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderstatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderstatus` (
  `pk_id_orderstatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_orderstatus`),
  UNIQUE INDEX `pk_idOrderStatus_UNIQUE` (`pk_id_orderstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`order` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`order` (
  `pk_id_order` INT NOT NULL AUTO_INCREMENT,
  `fk_id_orderstatus` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `creationtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_id_user` INT NULL,
  `fk_id_reservation` INT NULL,
  `fk_id_bill` INT NULL,
  PRIMARY KEY (`pk_id_order`),
  UNIQUE INDEX `idOrder_UNIQUE` (`pk_id_order` ASC),
  INDEX `fk_order_customer1_idx` (`fk_id_user` ASC),
  INDEX `fk_order_reservation1_idx` (`fk_id_reservation` ASC),
  INDEX `fk_order_bill1_idx` (`fk_id_bill` ASC),
  INDEX `fk_order_orderStatus1_idx` (`fk_id_orderstatus` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `ordermgmt`.`customer` (`fk_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_reservation1`
    FOREIGN KEY (`fk_id_reservation`)
    REFERENCES `ordermgmt`.`reservation` (`pk_id_reservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_bill1`
    FOREIGN KEY (`fk_id_bill`)
    REFERENCES `ordermgmt`.`bill` (`pk_id_bill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_orderStatus1`
    FOREIGN KEY (`fk_id_orderstatus`)
    REFERENCES `ordermgmt`.`orderstatus` (`pk_id_orderstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderitemstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderitemstatus` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderitemstatus` (
  `pk_id_orderitemstatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_orderitemstatus`),
  UNIQUE INDEX `pk_idOrderItemStatus_UNIQUE` (`pk_id_orderitemstatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`foodtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`foodtype` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`foodtype` (
  `pk_idFoodType` INT NOT NULL AUTO_INCREMENT,
  `tax` DOUBLE NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_idFoodType`),
  UNIQUE INDEX `pk_idFoodType_UNIQUE` (`pk_idFoodType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`sizeunit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`sizeunit` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`sizeunit` (
  `pk_id_sizeunit` INT NOT NULL AUTO_INCREMENT,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_sizeunit`),
  UNIQUE INDEX `pk_idSizeUnit_UNIQUE` (`pk_id_sizeunit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`food` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`food` (
  `pk_id_food` INT NOT NULL AUTO_INCREMENT,
  `netto_price` DOUBLE NULL,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `fk_id_foodtype` INT NULL,
  `size` DOUBLE NULL,
  `fk_id_sizeunit` INT NULL,
  PRIMARY KEY (`pk_id_food`),
  UNIQUE INDEX `pk_idFood_UNIQUE` (`pk_id_food` ASC),
  INDEX `fk_food_foodType1_idx` (`fk_id_foodtype` ASC),
  INDEX `fk_food_sizeUnit1_idx` (`fk_id_sizeunit` ASC),
  CONSTRAINT `fk_food_foodType1`
    FOREIGN KEY (`fk_id_foodtype`)
    REFERENCES `ordermgmt`.`foodtype` (`pk_idFoodType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_sizeUnit1`
    FOREIGN KEY (`fk_id_sizeunit`)
    REFERENCES `ordermgmt`.`sizeunit` (`pk_id_sizeunit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`orderitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`orderitem` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`orderitem` (
  `pk_id_orderitem` INT NOT NULL AUTO_INCREMENT,
  `fk_id_orderitemstatus` INT NULL,
  `comment` VARCHAR(1023) NULL,
  `fk_id_order` INT NULL,
  `fk_id_food` INT NULL,
  PRIMARY KEY (`pk_id_orderitem`),
  UNIQUE INDEX `idOrderItem_UNIQUE` (`pk_id_orderitem` ASC),
  INDEX `fk_orderItem_order1_idx` (`fk_id_order` ASC),
  INDEX `fk_orderItem_orderItemStatus1_idx` (`fk_id_orderitemstatus` ASC),
  INDEX `fk_orderItem_food1_idx` (`fk_id_food` ASC),
  CONSTRAINT `fk_orderItem_order1`
    FOREIGN KEY (`fk_id_order`)
    REFERENCES `ordermgmt`.`order` (`pk_id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItem_orderItemStatus1`
    FOREIGN KEY (`fk_id_orderitemstatus`)
    REFERENCES `ordermgmt`.`orderitemstatus` (`pk_id_orderitemstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItem_food1`
    FOREIGN KEY (`fk_id_food`)
    REFERENCES `ordermgmt`.`food` (`pk_id_food`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordermgmt`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordermgmt`.`test` ;

CREATE TABLE IF NOT EXISTS `ordermgmt`.`test` (
  `pk_id_test` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_id_test`),
  UNIQUE INDEX `pk_idTest_UNIQUE` (`pk_id_test` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
